apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-fashion-server
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: my-fashion-server 
        app: my-fashion-server
        tier: backend
        role: application-server
    spec:
      volumes: 
      - name: my-fashion-server-config
        configMap:
          name: my-fashion-server-config       
      containers:
      - name: trench-server 
        image: gcr.io/sample-project-1982/my-fashion-server:0.1
        imagePullPolicy: Always 
        command: ["npm","start",--,]
        args: ["/etc/config/config.json"]
        env:                        
        volumeMounts: 
          - name: my-fashion-server-config
            mountPath: "/etc/config"
            readOnly: true      
        ports:
        - containerPort: 1337       
        readinessProbe:
          httpGet:
            path: /health
            port: 1337
          initialDelaySeconds: 5
          timeoutSeconds: 1
                                       
                                      
           
      
                                                                 
              