apiVersion: v1
kind: Service
metadata:
  name: my-fashion-server
spec:
  ports:
  - port: 80
    targetPort: 1337 
    protocol: TCP
    name: my-fashion-server
  type: LoadBalancer 
  selector:
    app: my-fashion-server   